# Force Nixpacks (disable Docker)
[variables]
NIXPACKS_NODE_PACKAGE_MANAGER = "pnpm"
NODE_ENV = "production"
DISABLE_DOCKER = "true"

[providers]
node = "18.x"

[phases.setup]
nixPkgs = ["nodejs-18_x", "pnpm"]

[phases.build]
cmds = [
  "corepack enable",
  "pnpm install --frozen-lockfile", 
  "pnpm run build"
]

[phases.start]
cmd = "pnpm start -- -p ${PORT:-3000}"