# Configuración simple y correcta para Railway
[variables]
NIXPACKS_NODE_PACKAGE_MANAGER = "pnpm"
NODE_ENV = "production"

[phases.build]
cmds = [
  "corepack enable",
  "pnpm install --frozen-lockfile",
  "pnpm run build"
]

[phases.start]
cmd = "pnpm start"