[variables]
NIXPACKS_NODE_PACKAGE_MANAGER = "pnpm"   # ← fuerza pnpm
NODE_ENV = "production"

[phases.build]
cmds = [
  "corepack enable",                     # habilita pnpm
  "pnpm install --frozen-lockfile",
  "pnpm run build"
]

[phases.start]
cmd = "pnpm start -- -p ${PORT}"